"""empty message

Revision ID: 4b9c564a70a3
Revises: 
Create Date: 2019-11-14 15:52:51.876185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9c564a70a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chaves',
    sa.Column('id', sa.String(length=44), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Company',
    sa.Column('id', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NumberDocument',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('year', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', 'month', 'year')
    )
    op.create_table('Relationship',
    sa.Column('id_company', sa.String(length=14), nullable=False),
    sa.Column('id_numberDocument', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['id_numberDocument'], ['NumberDocument.id'], ),
    sa.PrimaryKeyConstraint('id_company', 'id_numberDocument')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Relationship')
    op.drop_table('NumberDocument')
    op.drop_table('Company')
    op.drop_table('Chaves')
    # ### end Alembic commands ###
