"""empty message

Revision ID: 7d880401bda0
Revises: 
Create Date: 2019-11-01 11:10:04.102451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d880401bda0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chaves',
    sa.Column('id', sa.String(length=44), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Chaves')
    # ### end Alembic commands ###
