"""empty message

Revision ID: cd5911f19002
Revises: 
Create Date: 2019-12-13 13:34:55.416347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5911f19002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type_random', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Keys',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('year', sa.String(length=2), nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('model', sa.String(length=2), nullable=False),
    sa.Column('serie', sa.String(length=3), nullable=False),
    sa.Column('issue', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('company_id', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Month',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('model', sa.String(length=2), nullable=False),
    sa.Column('serie', sa.String(length=3), nullable=False),
    sa.Column('issue', sa.String(length=1), nullable=False),
    sa.Column('inicial', sa.Integer(), nullable=False),
    sa.Column('returns', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id', 'state', 'year', 'model', 'serie', 'issue', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Month')
    op.drop_table('Keys')
    op.drop_table('Company')
    # ### end Alembic commands ###
