"""empty message

Revision ID: dc9b9a94e21e
Revises: 944c62f5021d
Create Date: 2019-10-30 11:47:17.845463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc9b9a94e21e'
down_revision = '944c62f5021d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chaves',
    sa.Column('id', sa.String(length=44), nullable=False),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chaves')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chaves',
    sa.Column('id', mysql.VARCHAR(length=44), nullable=False),
    sa.Column('verify', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('Chaves')
    # ### end Alembic commands ###
