"""empty message

Revision ID: e297be1275a0
Revises: 
Create Date: 2019-12-02 16:43:20.819929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e297be1275a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type_random', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NumberDocument',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('company_id', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Keys',
    sa.Column('id', sa.String(length=44), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('year', sa.String(length=2), nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('model', sa.String(length=2), nullable=False),
    sa.Column('serie', sa.String(length=2), nullable=False),
    sa.Column('issue', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('numberDocument_id', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['numberDocument_id'], ['NumberDocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Keys')
    op.drop_table('NumberDocument')
    op.drop_table('Company')
    # ### end Alembic commands ###
